[package]
name = "sync_mods"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-ini = "0.18"
winapi = {version = "0.3.9", features = ["securitybaseapi", "handleapi", "shellapi"] }
libc = "0.2.66"
